### PR TITLE
(WIP) V1: New terminology and structure

### PR DESCRIPTION
**Pull request by mato**
(WIP, DO NOT MERGE, can be rebased at any time)

This is an initial version of the new terminology and structure, as outlined in #172. The changes will be made in several parts (as individual commits in this PR):

1. [x] Introduce new directory structure and rename source files and build products.
2. [x] Rename internal symbols and APIs.
3. [x] Rename OPAM packaging. _Note: OPAM installation will not be functional until this step is completed and MirageOS dependencies are updated_
4. [ ] Sundry changes (e.g. mention of ukvm in license headers, etc.)
5. [ ] Documentation updates to reflect changes made.

See individual commits for a detailed description of changes.

/cc @ricarkol @djwillia Please follow along and shout if there's anything you'd like done differently wrt. naming. You can also review the changes themselves, but they will be big and a large chunk will be mechanical.

### CODE REVIEW

**Comment by samoht** [comment]
`hvt` sounds good to me :p

**Comment by djwillia** [comment]
`hvt` is fine with me as well

**Comment by djwillia** [comment]
at first I thought it might get confused with HVM in Xen, but now I kind of like how the `t` stands for tender

**Comment by ricarkol** [comment]
+1 on `hvt` hardware-virtualized tender

**Comment by hannesm** [comment]
`hvt` sounds good to me. as mentioned, I've a set of PRs around for a mirage 3.2.0 release (see https://github.com/mirage/mirage-protocols/pull/11, or directly https://github.com/mirage/mirage/pull/920, should not conflict with these changes), i can wait and do the mirage release whenever you're ready (to include both changes)

**Comment by mato** [comment]
@djwillia Good point about `hvt` == "hardware virtualised tender". Ok, so `hvt` it is then.

@hannesm Yes, let's coordinate this. I should be ready with the re-worked patches Mon/Tue, taking into account various CI/PR delays we should be able to release by the end of the week.

**Comment by hannesm** [comment]
@mato great. please PR the upper bounds (and conflicts) already to opam-repository

**Comment by mato** [comment]
Superseded by #274.

**Pull request closed without merging**
