### PR TITLE
configure.sh: make pkg-config and ar used for host configurable

### PR DESCRIPTION
**Pull request by sternenseemann**

### CODE REVIEW

**Comment by dinosaure** [comment]
Hi, thanks for this PR, can you confirm that Solo5 works for NixOS? I will be able to cut a minor release if you want.

**Comment by sternenseemann** [comment]
No, still some obstacles, these are just some low hanging fruits / non-invasive changes that I've found useful. If you want to follow the progress, you can look at <https://github.com/NixOS/nixpkgs/pull/153204>.

**Comment by dinosaure** [comment]
Thanks, if you want any help on our side, don't hesitate to call us 👍 ! On our side, I think we will move forward and release the rest of the MirageOS toolchain - we desperately want to cut a release before February. I'm currently working on the CI of Solo5 too and we will start to figure out how to integrate NixOS as a platform and how to test it systematically (as Debian, FreeBSD and OpenBSD) to finally help any of us.

**Comment by dinosaure** [comment]
4 years after, I was able to launch CI on your PR. I will try to see why we have an error on OpenBSD 7.2 and FreeBSD 14 (something is probably missing in these systems).

**Comment by dinosaure** [comment]
Ok, the CI looks good now, the PR seems ok and I like the idea to be able to define `HOST_AR` and `HOST_PKG_CONFIG` :+1:. Let's merge and sorry for the long delay.

**Pull request merged**
