### PR TITLE
Enable printf-style parameter check for log() function

### PR DESCRIPTION
**Pull request by xiaobo55x**
Add __attribute__ ((format (printf, 2, 3))) to log() function
to enable printf-style parameter check.

Signed-off-by: Haibo Xu <haibo.xu@arm.com>

### CODE REVIEW

**Comment by xiaobo55x** [comment]
@mato I have fixed the log() function issue #306 in this PR. Please help have a look.

**Comment by mato** [comment]
@xiaobo55x Thank you for fixing this, including the invocations! The changes look fine. Would you mind rebasing this into a single commit and force-pushing the branch? Also, please mention in the commit log that you're also fixing the invocations to match the updated definition.

**Comment by xiaobo55x** [comment]
@mato Ok, will send a new PR soon!

**Comment by mato** [comment]
Superseded by #308

**Pull request closed without merging**
