### PR TITLE
Memory layout fixes

### PR DESCRIPTION
**Pull request by mato**
Summary of changes:
- New, unified, linker scripts for ukvm and virtio. Addresses #73.
- Mainly cosmetic changes to link order and bootstrap stack placement. Makes eyeballing the symbol table for correctness easier.

### CODE REVIEW

**Comment by mato** [comment]
@hannesm Could you test this on FreeBSD to check it's not broken there?

**Comment by mato** [comment]
I've tested this change against @pqwy's `abstract-type` test case and everything works.

`-t virtio`:
````
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
multiboot: Using memory: 0x100000 - 0x7fe0000
Initializing the KVM Paravirtualized clock.
Solo5: new bindings
STUB: getenv() called
+ ops: ops: 3161824, id: 2484551, compare: 2265792, hash: 2265824
+ ops: ops: 3161760, id: 2484548, compare: 2265904, hash: 2265840
+ ops: ops: 3162528, id: 2482125, compare: 1814624, hash: 1815056
+ ops: ops: 3162464, id: 2482013, compare: 1813552, hash: 1813568
ptr: 2482007

solo5_app_main() returned with 0
Kernel done.
Goodbye!
````

`-t ukvm`:
````
Setting the CPUID.
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
mem_size=20000000, kernel_end=30d000
Initializing the KVM Paravirtualized clock.
Solo5: new bindings
STUB: getenv() called
+ ops: ops: 3128928, id: 2459111, compare: 2239232, hash: 2239264
+ ops: ops: 3128864, id: 2459108, compare: 2239344, hash: 2239280
+ ops: ops: 3129632, id: 2456685, compare: 1788080, hash: 1788512
+ ops: ops: 3129568, id: 2456573, compare: 1787008, hash: 1787024
ptr: 2456567

solo5_app_main() returned with 0
Kernel done.
Goodbye!
KVM_EXIT_HLT
````
Also, `static_website_tls` (see #74) now works for me for both `ukvm` and `virtio`.

**Comment by djwillia** [comment]
looks good to me.  again, great job tracking this down

**Comment by hannesm** [comment]
thanks mato, the console examples work fine on FreeBSD with this change (still no virtio on FreeBSD due to lack of time to investigate)!

**Comment by mato** [comment]
@hannesm Thanks for testing. Merging...

**Comment by pqwy** [comment]
Awesome work, thanks!

**Pull request merged**
