### PR TITLE
tenders, bindings, mfttool: Embed version information

### LINKED ISSUE #323: add git manifest to facilitate debug
It would be nice if we could add some kind of manifest for the commit hash, and print it out on solo5's preamble.

This came up while working on the aarch64 port of rumprun/solo5. We could add that on rumprun [nabla-containers/rumprun/issues/17] without having to touch solo5, but I suspect that would be potentially useful for other unikernel/port attempts, so maybe we could split it and add the current commit on each one of the layers.  

What we had in mind is something along the lines of the following rough patch (for hvt & spt).

```
diff --git a/bindings/hvt/start.c b/bindings/hvt/start.c
index 0d224b0..960bc8f 100644
--- a/bindings/hvt/start.c
+++ b/bindings/hvt/start.c
@@ -37,6 +37,7 @@ void _start(void *arg)
     log(INFO, "  __|  _ \\  |  _ \\ __ \\\n");
     log(INFO, "\\__ \\ (   | | (   |  ) |\n");
     log(INFO, "____/\\___/ _|\\___/____/\n");
+    log(INFO, "Solo5: git: %x\n", VERSION);
 
     mem_init();
     time_init(arg);
diff --git a/bindings/spt/start.c b/bindings/spt/start.c
index e58eed2..07edc91 100644
--- a/bindings/spt/start.c
+++ b/bindings/spt/start.c
@@ -34,7 +34,7 @@ void _start(void *arg)
     log(INFO, "  __|  _ \\  |  _ \\ __ \\\n");
     log(INFO, "\\__ \\ (   | | (   |  ) |\n");
     log(INFO, "____/\\___/ _|\\___/____/\n");
-
+    log(INFO, "Solo5: git: %x\n", VERSION);
     mem_init();
     block_init(arg);
     net_init(arg);
diff --git a/configure.sh b/configure.sh
index 77ef415..0602698 100755
--- a/configure.sh
+++ b/configure.sh
@@ -217,6 +217,9 @@ case $(uname -s) in
         ;;
 esac
 
+VERSION=`git rev-parse --verify HEAD --short`
+HOST_CFLAGS="$HOST_CFLAGS -DVERSION=0x'${VERSION}'"
+
 cat <<EOM >Makeconf
 # Generated by configure.sh, using CC=${CC} for target ${TARGET}
 BUILD_HVT=${BUILD_HVT}
```

Please let us know your thoughts!

thanks!

### PR DESCRIPTION
**Pull request by mato**
Generate a common include/solo5/solo5_version.h every time `make` is invoked _and_ the Git version, as defined by the output of `git -C . describe --dirty --tags --always` changes.

Embed this information and make it available in the tenders (via --version), mfttool (in the help, and in the generated manifest), and during bindings startup.

Results:

```
$ tenders/hvt/solo5-hvt --version
solo5-hvt v0.4.1-161-gcaa0b1f
$ tenders/hvt/solo5-hvt tests/test_hello/test_hello.hvt
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Bindings version v0.4.1-161-gcaa0b1f
[...]
$ mfttool/solo5-mfttool
usage: solo5-mfttool COMMAND ...
solo5-mfttool version v0.4.1-161-gcaa0b1f

COMMAND is:
[...]
$ head -1 tests/test_hello/manifest.c 
/* Generated by solo5-mfttool version v0.4.1-161-gcaa0b1f, do not edit */
```

Fixes #323. /cc @ananos @hannesm @ricarkol

### CODE REVIEW

**Comment by hannesm** [comment]
this is nice, one question I have: when there is a release of solo5, the release tarball should include a static `include/solo5/solo5_version.h` file with the version information, no (this could be achieved by documenting the release steps: (a) create a branch, (b) create that file `solo5_version.h` (and `git add && git commit`), (c) tag the release)? it'd imho be greatly appreciated to not depend on `git` for building solo5 releases.

**Comment by mato** [comment]
> this is nice, one question I have: when there is a release of solo5, the release tarball should include a static `include/solo5/solo5_version.h` file with the version information, no (this could be achieved by documenting the release steps: (a) create a branch, (b) create that file `solo5_version.h` (and `git add && git commit`), (c) tag the release)? it'd imho be greatly appreciated to not depend on `git` for building solo5 releases.

Good point. I don't want to have generated files in git, even on branches, unless necessary. I'll see what I can come up with.

**Comment by hannesm** [comment]
@mato what I've seen elsewhere is to pass it around via the build system, i.e. `make SOLO5_VERSION=0.42` in the opam file (or whereever else make is invoked) -- at some point I'd expect the solo5 tender to be an operating system (debian/FreeBSD/...) package, which would then need the version information to pass to make.

**Comment by mato** [comment]
@hannesm Okay, how about 00f2e08? It's a bit roundabout, but at the end of the day provides a `make distrib`, which magically does the right thing and a release tarball with a pre-generated `solo5_version.h.distrib` in it pops out. At build time, the script notices it's not in a Git tree and uses that file as its source of truth.

It may still need some tweaking, I'll get to that while making a release.

**Comment by hannesm** [comment]
@mato that looks fine to me (but now a release is slightly more involved than clicking on github's "draft a release" button -- which is imho fine, but I'd document the steps to make a release)

**Comment by mato** [comment]
@hannesm I agree that the release process needs documenting, and I'll do that around the time we actually cut the next release.

I've pushed a few more tweaks, cleaning up the release tarballs somewhat and also adding `make distrib` to CI. Will merge this now, it can be improved later.

**Pull request merged**
