### PR TITLE
Refactor interrupt and trap handlers

### PR DESCRIPTION
**Pull request by mato**
Part of #82 ("Clean up interrupt and trap handlers").

### CODE REVIEW

**Comment by mato** [comment]
@ricarkol @djwillia Please review. This is a fairly large change all over, but hopefully for the better (looking at LOC deleted vs. added). I've tested the rewritten trap handlers with manually written code triggering `#DE` and `#PF` and all seems fine. Likewise, the standalone tests pass muster with the new irq handlers.

**Comment by ricarkol** [comment]
taking a look @mato

**Comment by mato** [comment]
@hannesm Asking for the obligatory test on FreeBSD for this when you have a chance, just to ensure I haven't screwed anything up :-)

**Comment by ricarkol** [comment]
lgtm

Tested with the static_website and stackv4 unikernels locally and in GCE. Also tested triggering various interrupts by hand with `int` at various places. Also tested ukvm test_ping_serve and test_blk just in case. All good.

**Comment by hannesm** [comment]
@mato same as usual on FreeBSD/bhyve: interrupts are handled well, but all that is send are zero bytes (see #94).  Thanks (this code looks much cleaner than the previous one)!

**Pull request merged**
